# Generated by Django 3.1.2 on 2020-10-07 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='advertise',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='educational_status',
            field=models.PositiveIntegerField(choices=[(0, 'Ilkokul'), (1, 'Lise'), (2, 'Universite')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Kadın'), (1, 'Erkek')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='martial_status',
            field=models.PositiveIntegerField(choices=[(0, 'Evli'), (1, 'Bekar')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.PositiveIntegerField(choices=[(0, 'Ozel Sektor'), (1, 'Ogrenci'), (2, 'Kamu Calısanı'), (3, 'Ev Hanımı'), (4, 'Calısmıyorum'), (5, 'Emekli')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(to='advertise.Interest'),
        ),
    ]
